name: redeveiculos_flutter
description: Redeveiculos.com Rastreamento

publish_to: 'none'

version: 6.2.4+62004

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  onesignal_flutter: ^3.5.2
  shared_preferences: ^2.2.2
  wakelock: ^0.6.2
  url_launcher: ^6.2.5
  map_launcher: ^3.1.0
  flutter_svg: ^2.0.7
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.5
  flutter_downloader: ^1.11.1
  path_provider: ^2.1.0
  connectivity_plus: ^6.0.2
  app_tracking_transparency: ^2.0.4
  open_filex: ^4.3.2

  shared_preferences_web: any
  url_launcher_web: any
  wakelock_web: any
  flutter_web_plugins: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/js/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"
